# Generated by Django 6.0.5 on 2026-05-28 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(help_text='Unique Stripe event identifier (e.g., evt_xxx)', max_length=100, unique=True, verbose_name='Stripe event ID')),
                ('event_type', models.CharField(help_text='Stripe event type (e.g., customer.subscription.created)', max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(help_text='Complete Stripe event payload', verbose_name='payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether this event has been processed', verbose_name='processed')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', verbose_name='error message')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer may not be known when event is received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_events', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Stripe Event',
                'verbose_name_plural': 'Stripe Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['processed', 'received_at'], name='billing_stripe_event_queue'), models.Index(fields=['event_type'], name='billing_stripe_event_type')],
            },
        ),
    ]
