# Generated by Django 6.0.5 on 2026-05-28 07:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(help_text='Unique Stripe invoice identifier (e.g., in_xxx)', max_length=100, unique=True, verbose_name='Stripe invoice ID')),
                ('stripe_hosted_url', models.URLField(blank=True, help_text='URL to view invoice on Stripe', verbose_name='Stripe hosted URL')),
                ('stripe_pdf_url', models.URLField(blank=True, help_text='URL to download invoice PDF', verbose_name='Stripe PDF URL')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Total amount due on this invoice', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid on this invoice', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount paid')),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], help_text='Current status of the invoice', max_length=20, verbose_name='status')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start of the billing period', null=True, verbose_name='period start')),
                ('period_end', models.DateTimeField(blank=True, help_text='End of the billing period', null=True, verbose_name='period end')),
                ('due_date', models.DateTimeField(blank=True, help_text='Date the invoice is due', null=True, verbose_name='due date')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date the invoice was paid', null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(help_text='Customer who owns this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='customer')),
                ('subscription', models.ForeignKey(blank=True, help_text='Associated subscription (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='billing_inv_cust_stat')],
            },
        ),
    ]
