# Generated by Django 6.0.5 on 2026-05-31 06:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice'),
        ('customers', '0004_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique coupon code (e.g., RESELLER2026)', max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Internal name for identification', max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10, verbose_name='discount type')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0.01 - 100.00)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='discount percentage')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount in EUR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='discount amount')),
                ('duration', models.CharField(choices=[('repeating', 'Repeating'), ('forever', 'Forever')], max_length=10, verbose_name='duration')),
                ('duration_in_months', models.PositiveIntegerField(blank=True, help_text='Number of months for repeating discount', null=True, verbose_name='duration in months')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be redeemed (null = unlimited)', null=True, verbose_name='maximum redemptions')),
                ('redemptions_count', models.PositiveIntegerField(default=0, help_text='Current number of redemptions', verbose_name='redemptions count')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start date for validity (null = immediately valid)', null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, help_text='End date for validity (null = no expiration)', null=True, verbose_name='valid until')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon can be used', verbose_name='active')),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe coupon ID (co_...)', max_length=100, verbose_name='Stripe coupon ID')),
                ('stripe_promotion_code_id', models.CharField(blank=True, help_text='Stripe promotion code ID (promo_...)', max_length=100, verbose_name='Stripe promotion code ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='redeemed at')),
                ('stripe_discount_id', models.CharField(blank=True, help_text='Stripe discount ID on the subscription', max_length=100, verbose_name='Stripe discount ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.coupon', verbose_name='coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='customers.customer', verbose_name='customer')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='customers.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupon Redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='billing_coupon_code'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_until'], name='billing_coupon_validity'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'redeemed_at'], name='billing_redemption_coupon'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['customer', 'redeemed_at'], name='billing_redemption_customer'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'customer'), name='unique_coupon_customer'),
        ),
    ]
