# Generated by Django 6.0.5 on 2026-05-31 06:20

from django.db import migrations
from decimal import Decimal
import uuid


def create_internal_coupon(apps, schema_editor):
    """
    Create the INTERNAL coupon for internal use (100% discount, permanent).
    Note: This does NOT sync to Stripe - that must be done manually in the admin.
    """
    Coupon = apps.get_model('billing', 'Coupon')

    # Check if INTERNAL coupon already exists
    if Coupon.objects.filter(code='INTERNAL').exists():
        return

    Coupon.objects.create(
        id=uuid.uuid4(),
        code='INTERNAL',
        name='Interne Instanzen',
        type='percent',
        discount_percent=Decimal('100.00'),
        discount_amount=None,
        duration='forever',
        duration_in_months=None,
        max_redemptions=None,  # Unlimited
        redemptions_count=0,
        valid_from=None,  # Immediately valid
        valid_until=None,  # Never expires
        is_active=True,
        stripe_coupon_id='',  # Will be filled when manually synced
        stripe_promotion_code_id='',  # Will be filled when manually synced
        created_by=None,  # System-created
    )


def reverse_internal_coupon(apps, schema_editor):
    """
    Remove the INTERNAL coupon if migration is reversed.
    """
    Coupon = apps.get_model('billing', 'Coupon')
    Coupon.objects.filter(code='INTERNAL').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_coupon_couponredemption_coupon_billing_coupon_code_and_more'),
    ]

    operations = [
        migrations.RunPython(create_internal_coupon, reverse_internal_coupon),
    ]

