# Generated by Django 6.0.5 on 2026-05-31 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_internal_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', help_text='test or live mode', max_length=10, verbose_name='mode')),
                ('test_secret_key', models.CharField(blank=True, help_text='sk_test_... (encrypted)', max_length=500, verbose_name='test secret key')),
                ('test_publishable_key', models.CharField(blank=True, help_text='pk_test_...', max_length=200, verbose_name='test publishable key')),
                ('test_webhook_secret', models.CharField(blank=True, help_text='whsec_... (encrypted)', max_length=500, verbose_name='test webhook secret')),
                ('live_secret_key', models.CharField(blank=True, help_text='sk_live_... (encrypted)', max_length=500, verbose_name='live secret key')),
                ('live_publishable_key', models.CharField(blank=True, help_text='pk_live_...', max_length=200, verbose_name='live publishable key')),
                ('live_webhook_secret', models.CharField(blank=True, help_text='whsec_... (encrypted)', max_length=500, verbose_name='live webhook secret')),
                ('webhook_endpoint_id', models.CharField(blank=True, help_text='we_...', max_length=100, verbose_name='webhook endpoint ID')),
                ('webhook_last_received_at', models.DateTimeField(blank=True, null=True, verbose_name='webhook last received at')),
                ('webhook_last_event_type', models.CharField(blank=True, max_length=100, verbose_name='webhook last event type')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Stripe Configuration',
                'verbose_name_plural': 'Stripe Configuration',
            },
        ),
    ]
