# Generated by Django 6.0.5 on 2026-05-28 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('trigger', models.CharField(choices=[('subscriber_confirmed', 'Subscriber Confirmed'), ('customer_created', 'Customer Created'), ('manual', 'Manual')], max_length=30, verbose_name='trigger')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Automation Sequence',
                'verbose_name_plural': 'Automation Sequences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Internal name', max_length=200, verbose_name='name')),
                ('subject', models.CharField(help_text='Email subject', max_length=300, verbose_name='subject')),
                ('preview_text', models.CharField(blank=True, help_text='Preview text in email client', max_length=200, verbose_name='preview text')),
                ('html_body', models.TextField(help_text='HTML content', verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, help_text='Plaintext fallback', verbose_name='text body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('segment', models.CharField(choices=[('all', 'All'), ('leads', 'Leads'), ('customers', 'Customers'), ('manual', 'Manual')], default='all', help_text='all: all active subscribers | leads: subscribers with linked Contact (not converted) | customers: subscribers who are also Customer (via email match) | manual: manually selected subscribers', max_length=20, verbose_name='segment')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Planned send time', null=True, verbose_name='scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Filled on send', verbose_name='recipient count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='active', max_length=20, verbose_name='status')),
                ('source', models.CharField(choices=[('web_form', 'Web Form'), ('contact_form', 'Contact Form'), ('manual', 'Manual'), ('api', 'API')], max_length=20, verbose_name='source')),
                ('unsubscribe_token', models.CharField(editable=False, help_text='Auto-generated via secrets.token_urlsafe', max_length=64, unique=True, verbose_name='unsubscribe token')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='subscribed at')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='unsubscribed at')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Subscription IP for GDPR', null=True, verbose_name='IP address')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='For Double-Opt-In', null=True, verbose_name='confirmed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contact', models.ForeignKey(blank=True, help_text='Link if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='crm.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order within sequence', verbose_name='order')),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Offset to previous step', verbose_name='delay days')),
                ('subject', models.CharField(max_length=300, verbose_name='subject')),
                ('preview_text', models.CharField(blank=True, max_length=200, verbose_name='preview text')),
                ('html_body', models.TextField(verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, verbose_name='text body')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='newsletter.automationsequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Sequence Step',
                'verbose_name_plural': 'Sequence Steps',
                'ordering': ['sequence', 'order'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'order'), name='unique_sequence_order')],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.PositiveIntegerField(default=0, verbose_name='current step')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('next_send_at', models.DateTimeField(blank=True, help_text='When the next step will be sent', null=True, verbose_name='next send at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='newsletter.automationsequence', verbose_name='sequence')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='newsletter.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Sequence Enrollment',
                'verbose_name_plural': 'Sequence Enrollments',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'subscriber'), name='unique_sequence_subscriber')],
            },
        ),
        migrations.CreateModel(
            name='CampaignMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_mails', to='newsletter.campaign', verbose_name='campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_mails', to='newsletter.subscriber', verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'Campaign Mail',
                'verbose_name_plural': 'Campaign Mails',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscriber'), name='unique_campaign_subscriber')],
            },
        ),
    ]
