# Generated by Django 6.0.5 on 2026-05-27 21:06

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='plan name')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('max_users_per_instance', models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='max users per instance')),
                ('max_instances', models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='max instances')),
                ('price_per_user', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='€/User/Month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price per user')),
                ('price_per_instance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='€/Instance/Month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price per instance')),
                ('price_ai_addon', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='€/AI-Addon/Month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price AI addon')),
                ('ai_addon_available', models.BooleanField(default=False, verbose_name='AI addon available')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe product ID')),
                ('stripe_price_id_user', models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID (user)')),
                ('stripe_price_id_instance', models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID (instance)')),
                ('stripe_price_id_ai', models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID (AI)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be booked for new subscriptions', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['name'],
            },
        ),
    ]
