# Generated by Django 6.0.5 on 2026-05-27 21:07

from django.db import migrations
from decimal import Decimal


def populate_initial_plans(apps, schema_editor):
    """
    Create initial plans with reference pricing from project requirements.
    Reference values:
    - User-Lizenz: 19 €/User/Monat
    - Instanzgebühr: 5 €/Instanz/Monat
    - KI-Addon: 7,50 €/Monat (200k Token/Woche)
    """
    Plan = apps.get_model('customers', 'Plan')

    plans = [
        {
            'name': 'starter',
            'display_name': 'Starter',
            'description': 'Basic plan for small teams getting started',
            'max_users_per_instance': 0,  # unlimited
            'max_instances': 0,  # unlimited
            'price_per_user': Decimal('19.00'),
            'price_per_instance': Decimal('5.00'),
            'price_ai_addon': Decimal('7.50'),
            'ai_addon_available': True,
            'is_active': True,
        },
        {
            'name': 'professional',
            'display_name': 'Professional',
            'description': 'Professional plan for growing businesses',
            'max_users_per_instance': 0,  # unlimited
            'max_instances': 0,  # unlimited
            'price_per_user': Decimal('19.00'),
            'price_per_instance': Decimal('5.00'),
            'price_ai_addon': Decimal('7.50'),
            'ai_addon_available': True,
            'is_active': True,
        },
        {
            'name': 'enterprise',
            'display_name': 'Enterprise',
            'description': 'Enterprise plan with premium features',
            'max_users_per_instance': 0,  # unlimited
            'max_instances': 0,  # unlimited
            'price_per_user': Decimal('19.00'),
            'price_per_instance': Decimal('5.00'),
            'price_ai_addon': Decimal('7.50'),
            'ai_addon_available': True,
            'is_active': True,
        },
    ]

    for plan_data in plans:
        Plan.objects.create(**plan_data)


def reverse_populate_initial_plans(apps, schema_editor):
    """Remove the initial plans."""
    Plan = apps.get_model('customers', 'Plan')
    Plan.objects.filter(name__in=['starter', 'professional', 'enterprise']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_plans, reverse_populate_initial_plans),
    ]
