# Generated by Django 6.0.5 on 2026-05-27 22:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_populate_initial_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='2-10 lowercase alphanumeric characters. Immutable after creation.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must be 2-10 lowercase alphanumeric characters (a-z, 0-9)', regex='^[a-z0-9]{2,10}$')], verbose_name='slug')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('contact_name', models.CharField(max_length=200, verbose_name='contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='billing email')),
                ('billing_address', models.CharField(max_length=255, verbose_name='billing address')),
                ('billing_city', models.CharField(max_length=100, verbose_name='billing city')),
                ('billing_postal_code', models.CharField(max_length=20, verbose_name='billing postal code')),
                ('billing_country', models.CharField(default='DE', help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='billing country')),
                ('vat_id', models.CharField(blank=True, help_text='Value Added Tax identification number', max_length=30, verbose_name='VAT ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stripe customer ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, not visible to customer', verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['company_name'],
            },
        ),
    ]
