# Generated by Django 6.0.5 on 2026-05-28 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True, verbose_name='Stripe subscription ID')),
                ('stripe_status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('paused', 'Paused')], max_length=30, verbose_name='Stripe status')),
                ('user_seats_total', models.PositiveIntegerField(default=1, verbose_name='total user seats')),
                ('instance_seats_total', models.PositiveIntegerField(default=1, verbose_name='total instance seats')),
                ('ai_addon_active', models.BooleanField(default=False, verbose_name='AI addon active')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='trial end')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer', verbose_name='customer')),
                ('plan', models.ForeignKey(help_text='Plan remains protected even if modified', on_delete=django.db.models.deletion.PROTECT, to='customers.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
