# Generated by Django 6.0.5 on 2026-05-31 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_coupon_couponredemption_coupon_billing_coupon_code_and_more'),
        ('customers', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon code for discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.coupon', verbose_name='coupon'),
        ),
    ]
