# Generated by Django 6.0.6 on 2026-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_subscription_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Applied coupon code', max_length=50, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon_description',
            field=models.CharField(blank=True, help_text='Human-readable coupon description', max_length=255, verbose_name='coupon description'),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (if applicable)', max_digits=5, null=True, verbose_name='coupon discount %'),
        ),
    ]
