# Generated by Django 6.0.6 on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_subscription_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ai_addon_cancelled_at',
            field=models.DateField(
                blank=True,
                help_text='KI-Addon läuft bis zu diesem Datum',
                null=True,
                verbose_name='AI addon cancelled at',
            ),
        ),
    ]
