# Generated by Django 6.0.5 on 2026-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_ai_addon_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='plan name'),
        ),
    ]
