# Generated by Django 6.0.5 on 2026-07-17 21:01

from decimal import Decimal

from django.db import migrations


def migrate_plan_data(apps, schema_editor):
    """
    Align seeded plans with the real offering: standard (Stripe) + enterprise
    (manual/contract only). 'starter' becomes 'standard' in place so existing
    subscriptions keep their FK. 'professional' never corresponded to a real
    offering, so it is removed outright unless a subscription already points
    at it, in which case it is only deactivated to avoid breaking that FK.
    """
    Plan = apps.get_model('customers', 'Plan')
    Subscription = apps.get_model('customers', 'Subscription')

    standard_plan = Plan.objects.filter(name='starter').first()
    if standard_plan:
        standard_plan.name = 'standard'
        standard_plan.display_name = 'Standard'
        standard_plan.save(update_fields=['name', 'display_name'])

    professional_plan = Plan.objects.filter(name='professional').first()
    if professional_plan:
        if Subscription.objects.filter(plan=professional_plan).exists():
            professional_plan.is_active = False
            professional_plan.save(update_fields=['is_active'])
        else:
            professional_plan.delete()

    Plan.objects.filter(name='enterprise').update(is_active=False)


def reverse_migrate_plan_data(apps, schema_editor):
    """Best-effort reversal: restore the original seeded starter/professional/enterprise state."""
    Plan = apps.get_model('customers', 'Plan')

    standard_plan = Plan.objects.filter(name='standard').first()
    if standard_plan:
        standard_plan.name = 'starter'
        standard_plan.display_name = 'Starter'
        standard_plan.save(update_fields=['name', 'display_name'])

    Plan.objects.get_or_create(
        name='professional',
        defaults={
            'display_name': 'Professional',
            'description': 'Professional plan for growing businesses',
            'price_per_user': Decimal('19.00'),
            'price_per_instance': Decimal('5.00'),
            'price_ai_addon': Decimal('7.50'),
            'ai_addon_available': True,
            'is_active': True,
        },
    )

    Plan.objects.filter(name='enterprise').update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_plan_choices_standard_enterprise'),
    ]

    operations = [
        migrations.RunPython(migrate_plan_data, reverse_migrate_plan_data),
    ]
