# Generated by Django 6.0.5 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_zero_price_per_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_ai_yearly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID (AI, yearly)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_user_yearly',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe price ID (user, yearly)'),
        ),
    ]
