# Generated by Django 6.0.5 on 2026-05-28 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.UUIDField(blank=True, help_text='Instance UUID (no FK to avoid circular imports)', null=True, verbose_name='instance ID')),
                ('actor_email', models.EmailField(help_text='Email of the actor performing the action, or "system" for automated actions', max_length=254, verbose_name='actor email')),
                ('actor_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True, verbose_name='actor IP')),
                ('action', models.CharField(help_text='Action performed (e.g., customer.created, instance.provisioned)', max_length=100, verbose_name='action')),
                ('resource_type', models.CharField(help_text='Type of resource affected (e.g., Customer, Instance)', max_length=50, verbose_name='resource type')),
                ('resource_id', models.CharField(help_text='ID of the resource affected', max_length=100, verbose_name='resource ID')),
                ('before', models.JSONField(blank=True, help_text='State before the action (if applicable)', null=True, verbose_name='before')),
                ('after', models.JSONField(blank=True, help_text='State after the action (if applicable)', null=True, verbose_name='after')),
                ('note', models.TextField(blank=True, help_text='Additional notes or context', verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('customer', models.ForeignKey(blank=True, help_text='Associated customer (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='audit_cust_created'), models.Index(fields=['action'], name='audit_action'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource')],
            },
        ),
    ]
