# Generated by Django 6.0.5 on 2026-05-31 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_stripeconfig'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(help_text='Name of the educational institution', max_length=200, verbose_name='institution name')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254, verbose_name='email')),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('school', 'School'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], default='other', max_length=50, verbose_name='institution type')),
                ('website', models.URLField(blank=True, help_text='Institution website', verbose_name='website')),
                ('description', models.TextField(blank=True, help_text='How the institution plans to use Zenico', verbose_name='description')),
                ('user_count', models.PositiveIntegerField(help_text='Estimated number of users', verbose_name='estimated user count')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For GDPR traceability', null=True, verbose_name='IP address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes for review', verbose_name='internal notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('coupon', models.ForeignKey(blank=True, help_text='Auto-created coupon when approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_requests', to='billing.coupon', verbose_name='coupon')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_education_requests', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'Education Request',
                'verbose_name_plural': 'Education Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
