# Generated by Django 6.0.5 on 2026-05-28 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='2-10 lowercase alphanumeric characters. For master instances, must match customer slug.', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must be 2-10 lowercase alphanumeric characters (a-z, 0-9)', regex='^[a-z0-9]{2,10}$')], verbose_name='slug')),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('is_master', models.BooleanField(default=False, verbose_name='is master')),
                ('server_host', models.CharField(blank=True, help_text='Hostname of the server where this instance is deployed', max_length=255, verbose_name='server host')),
                ('db_name', models.CharField(blank=True, max_length=255, verbose_name='database name')),
                ('db_user', models.CharField(blank=True, max_length=255, verbose_name='database user')),
                ('api_key', models.CharField(editable=False, help_text='Auto-generated API key for instance authentication', max_length=64, unique=True, verbose_name='API key')),
                ('django_secret_key', models.CharField(blank=True, max_length=100, verbose_name='Django secret key')),
                ('version', models.CharField(blank=True, help_text='Zenico version running on this instance', max_length=30, verbose_name='version')),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('deprovisioned', 'Deprovisioned')], default='provisioning', max_length=20, verbose_name='status')),
                ('user_seats', models.PositiveIntegerField(default=1, help_text='Number of user seats allocated to this instance', verbose_name='user seats')),
                ('ai_addon_active', models.BooleanField(default=False, verbose_name='AI addon active')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='provisioned at')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='last health check')),
                ('health_check_ok', models.BooleanField(blank=True, null=True, verbose_name='health check OK')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='customers.customer', verbose_name='customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='customers.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'ordering': ['customer', '-is_master', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'slug'), name='unique_slug_per_customer', violation_error_message='This slug is already used by another instance for this customer.'), models.UniqueConstraint(condition=models.Q(('is_master', True)), fields=('customer', 'is_master'), name='unique_master_per_customer', violation_error_message='Each customer can have only one master instance.')],
            },
        ),
    ]
