# Generated by Django 6.0.5 on 2026-05-28 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('azure_oid', models.CharField(help_text='Azure AD Object ID of the user', max_length=100, verbose_name='Azure AD Object ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('display_name', models.CharField(max_length=150, verbose_name='display name')),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('contributor', 'Contributor')], default='contributor', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this license is currently active', verbose_name='active')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='activated at')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='deactivated at')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_licenses', to='instances.instance', verbose_name='instance')),
            ],
            options={
                'verbose_name': 'User License',
                'verbose_name_plural': 'User Licenses',
                'ordering': ['instance', 'email'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'azure_oid'), name='unique_azure_oid_per_instance', violation_error_message='This Azure user is already licensed on this instance.')],
            },
        ),
    ]
