# Generated by Django 6.0.5 on 2026-06-02 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_userlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last phone-home call', null=True, verbose_name='last heartbeat'),
        ),
        migrations.AddField(
            model_name='instance',
            name='reported_active_users',
            field=models.PositiveIntegerField(default=0, help_text='Number of active users reported by the instance', verbose_name='reported active users'),
        ),
        migrations.AddField(
            model_name='instance',
            name='reported_url',
            field=models.URLField(blank=True, help_text='URL reported by the instance during phone-home', verbose_name='reported URL'),
        ),
        migrations.AddField(
            model_name='instance',
            name='reported_version',
            field=models.CharField(blank=True, help_text='Version reported by the instance during phone-home', max_length=30, verbose_name='reported version'),
        ),
        migrations.CreateModel(
            name='InstanceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='URL reported by the instance', verbose_name='URL')),
                ('version', models.CharField(help_text='Version reported by the instance', max_length=30, verbose_name='version')),
                ('active_users', models.PositiveIntegerField(help_text='Number of active users reported', verbose_name='active users')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the instance', null=True, verbose_name='IP address')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='instances.instance', verbose_name='instance')),
            ],
            options={
                'verbose_name': 'Instance Heartbeat',
                'verbose_name_plural': 'Instance Heartbeats',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(help_text='AI model used, e.g. "gpt-4o", "claude-sonnet-4-6"', max_length=100, verbose_name='AI model')),
                ('tokens_in', models.PositiveIntegerField(help_text='Input tokens used in this request', verbose_name='tokens in')),
                ('tokens_out', models.PositiveIntegerField(help_text='Output tokens used in this request', verbose_name='tokens out')),
                ('week_start', models.DateField(help_text='Monday of the calendar week (for weekly aggregation)', verbose_name='week start')),
                ('month', models.DateField(help_text='First day of the month (for monthly aggregation)', verbose_name='month')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_usage', to='instances.instance', verbose_name='instance')),
            ],
            options={
                'verbose_name': 'AI Token Usage',
                'verbose_name_plural': 'AI Token Usage',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['instance', 'week_start'], name='idx_instance_week'), models.Index(fields=['instance', 'month'], name='idx_instance_month')],
            },
        ),
    ]
