# Generated by Django 6.0.6 on 2026-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_instance_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='cancelled_at',
            field=models.DateField(blank=True, help_text='Date when the instance subscription ends (cancellation effective date)', null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='instance',
            name='cancelled_missing_feature',
            field=models.CharField(blank=True, help_text='Specific feature that was missing (if reason=missing_feature)', max_length=255, verbose_name='missing feature'),
        ),
        migrations.AddField(
            model_name='instance',
            name='cancelled_reason',
            field=models.CharField(blank=True, help_text='Reason category: missing_feature, too_expensive, not_needed, switching, other', max_length=50, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='instance',
            name='cancelled_reason_text',
            field=models.TextField(blank=True, help_text='Free text explanation for cancellation', verbose_name='cancellation reason text'),
        ),
    ]
