# Generated by Django 6.0.5 on 2026-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_provisioning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_ready_mail_sent_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, an dem die "Instanz ist bereit"-Mail an den Kunden verschickt wurde', null=True, verbose_name='instance ready mail sent at'),
        ),
    ]
