# Generated by Django 6.0.5 on 2026-06-02 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0003_instance_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('provider_type', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Anthropic', 'Anthropic')], max_length=20, verbose_name='provider type')),
                ('api_key', models.CharField(help_text='Encrypted API key', max_length=500, verbose_name='API key (encrypted)')),
                ('organization_id', models.CharField(blank=True, max_length=255, verbose_name='organization ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('model_id', models.CharField(help_text='Model identifier used in API calls', max_length=255, verbose_name='model ID')),
                ('input_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=4, help_text='Price in USD per 1 million input tokens', max_digits=10, null=True, verbose_name='input price per 1M tokens (USD)')),
                ('output_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=4, help_text='Price in USD per 1 million output tokens', max_digits=10, null=True, verbose_name='output price per 1M tokens (USD)')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIJobsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(default='zenico.ai', max_length=255, verbose_name='agent name')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error'), ('Cached', 'Cached')], default='Pending', max_length=20, verbose_name='status')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='input tokens')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='output tokens')),
                ('costs', models.DecimalField(blank=True, decimal_places=6, help_text='Kosten in USD', max_digits=10, null=True, verbose_name='costs (USD)')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('from_cache', models.BooleanField(default=False, verbose_name='from cache')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='instances.instance', verbose_name='instance')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ai.aimodel', verbose_name='model')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ai.aiprovider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'AI Job History',
                'verbose_name_plural': 'AI Job History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique agent identifier', max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('role', models.TextField(help_text='System Prompt — Rolle und Kontext des Agenten', verbose_name='role (system prompt)')),
                ('task', models.TextField(help_text='User Prompt Template — Aufgabenbeschreibung', verbose_name='task (user prompt template)')),
                ('cache_enabled', models.BooleanField(default=True, verbose_name='cache enabled')),
                ('cache_ttl_seconds', models.IntegerField(default=300, help_text='Cache time-to-live in seconds', verbose_name='cache TTL (seconds)')),
                ('cache_version', models.IntegerField(default=1, help_text='Increment to invalidate all cached responses for this agent', verbose_name='cache version')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum tokens in response', verbose_name='max tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Sampling temperature (0.0-1.0)', verbose_name='temperature')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='ai.aimodel', verbose_name='model')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='ai.aiprovider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AITokenBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekly_limit', models.IntegerField(default=200000, help_text='Maximale Tokens pro Woche', verbose_name='weekly limit')),
                ('tokens_used_week', models.IntegerField(default=0, verbose_name='tokens used this week')),
                ('week_start', models.DateField(auto_now_add=True, verbose_name='week start')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_budget', to='instances.instance', verbose_name='instance')),
            ],
            options={
                'verbose_name': 'AI Token Budget',
                'verbose_name_plural': 'AI Token Budgets',
            },
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_provider_model', violation_error_message='This model ID already exists for this provider.'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['-timestamp'], name='ai_aijobshi_timesta_97a3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['instance', '-timestamp'], name='ai_aijobshi_instanc_173b15_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['status'], name='ai_aijobshi_status_f35903_idx'),
        ),
    ]
