# Generated by Django 6.0.5 on 2026-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagent',
            options={'ordering': ['context_type', 'sort_order', 'name'], 'verbose_name': 'AI Agent', 'verbose_name_plural': 'AI Agents'},
        ),
        migrations.AddField(
            model_name='aiagent',
            name='button_icon',
            field=models.CharField(default='bi-stars', help_text='Bootstrap Icon Klasse (z.B. "bi-magic"). Referenz: https://icons.getbootstrap.com', max_length=50),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='context_type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Projekt'), ('attachment', 'Anhang')], default='task', help_text='Wo wird dieser Agent in Zenico.app angezeigt?', max_length=20),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='display_description',
            field=models.CharField(blank=True, help_text='Kurze Beschreibung was der Agent macht (1 Satz, Tooltip in App)', max_length=255),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='display_name',
            field=models.CharField(blank=True, help_text='Kundenfreundlicher Button-Name (z.B. "Beschreibung verbessern"). Leer = technischer Name wird verwendet.', max_length=100),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Reihenfolge der Buttons in der App (aufsteigend, z.B. 10/20/30)'),
        ),
    ]
