# Generated by Django 6.0.5 on 2026-06-03 10:10

from django.db import migrations


def update_agent_display_data(apps, schema_editor):
    """Update existing agents with display metadata."""
    AIAgent = apps.get_model('ai', 'AIAgent')

    agent_configs = [
        {
            'name': 'text-to-title-generator',
            'context_type': 'task',
            'display_name': 'Titel generieren',
            'display_description': 'Generiert einen Titel aus der Beschreibung',
            'button_icon': 'bi-type-h1',
            'sort_order': 10,
        },
        {
            'name': 'text-optimization-agent',
            'context_type': 'task',
            'display_name': 'Beschreibung verbessern',
            'display_description': 'Verbessert Formulierung, Rechtschreibung und Grammatik',
            'button_icon': 'bi-magic',
            'sort_order': 20,
        },
        {
            'name': 'task-subtask-suggester',
            'context_type': 'task',
            'display_name': 'Sub-Tasks vorschlagen',
            'display_description': 'Schlägt passende Unteraufgaben vor',
            'button_icon': 'bi-diagram-3',
            'sort_order': 30,
        },
        {
            'name': 'task-checklist-suggester',
            'context_type': 'task',
            'display_name': 'Checkliste vorschlagen',
            'display_description': 'Erstellt eine strukturierte Schritt-für-Schritt Checkliste',
            'button_icon': 'bi-list-check',
            'sort_order': 40,
        },
        {
            'name': 'task-summarizer',
            'context_type': 'task',
            'display_name': 'Task zusammenfassen',
            'display_description': 'Erstellt eine kompakte Zusammenfassung des aktuellen Stands',
            'button_icon': 'bi-file-text',
            'sort_order': 50,
        },
        {
            'name': 'task-sp-estimator',
            'context_type': 'task',
            'display_name': 'Story Points schätzen',
            'display_description': 'Schätzt den Aufwand in Story Points (1 SP = 1 Stunde)',
            'button_icon': 'bi-hourglass-split',
            'sort_order': 60,
        },
    ]

    for config in agent_configs:
        AIAgent.objects.filter(name=config['name']).update(
            context_type=config['context_type'],
            display_name=config['display_name'],
            display_description=config['display_description'],
            button_icon=config['button_icon'],
            sort_order=config['sort_order'],
        )


def reverse_update_agent_display_data(apps, schema_editor):
    """Reset agent display data to defaults."""
    AIAgent = apps.get_model('ai', 'AIAgent')

    agent_names = [
        'text-to-title-generator',
        'text-optimization-agent',
        'task-subtask-suggester',
        'task-checklist-suggester',
        'task-summarizer',
        'task-sp-estimator',
    ]

    AIAgent.objects.filter(name__in=agent_names).update(
        context_type='task',
        display_name='',
        display_description='',
        button_icon='bi-stars',
        sort_order=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_agent_display_context'),
    ]

    operations = [
        migrations.RunPython(update_agent_display_data, reverse_update_agent_display_data),
    ]
