# Generated by Django 6.0.6 on 2026-07-15 21:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_ai_addon_cancelled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_seats', models.PositiveIntegerField(verbose_name='user seats')),
                ('ai_addon', models.BooleanField(default=False, verbose_name='AI addon')),
                ('slug', models.SlugField(help_text='2-10 lowercase alphanumeric characters. Wird bei Zahlung zum Customer-Slug.', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must be 2-10 lowercase alphanumeric characters (a-z, 0-9)', regex='^[a-z0-9]{2,10}$')], verbose_name='desired slug')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('contact_name', models.CharField(max_length=200, verbose_name='contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='billing email')),
                ('billing_address', models.CharField(blank=True, max_length=255, verbose_name='billing address')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='billing city')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='billing postal code')),
                ('billing_country', models.CharField(default='DE', help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='billing country')),
                ('vat_id', models.CharField(blank=True, max_length=30, verbose_name='VAT ID')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='terms accepted')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending_payment', max_length=20, verbose_name='status')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe checkout session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'status'], name='orders_orde_slug_8ead14_idx'), models.Index(fields=['stripe_checkout_session_id'], name='orders_orde_stripe__338ca2_idx')],
            },
        ),
    ]
