# Generated by Django 6.0.5 on 2026-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Determines which Stripe price (monthly/yearly) is used at checkout', max_length=10, verbose_name='billing interval'),
        ),
    ]
